### ISSUE TITLE
PHP Fatal error:  Class 'EasyPost\\EasyPost' not found 

### ISSUE THREAD

**Issue by rawunus** [curkle/Magento-EasyPostShipping#1]
PHP Fatal error:  Class 'EasyPost\EasyPost' not found in /var/www/yetidog/app/code/local/Curkle/EasyPost/Model/Carrier/Easypost.php on line 83, 
 referer: http://localhost/yetidog/index.php/checkout/onepage/

**Comment by curkle** [comment]
Version of Magneto?

**Comment by curkle** [comment]
It looks lib class can't be found, try to clear cache. and it required php 5.4

**Comment by rawunus** [comment]
version of Magento 1.9.1

**Comment by rawunus** [comment]
In lib folder there is use namespace magento 1.9.1 there is not use  namespace autoloader.

**Comment by curkle** [comment]
sorry for late reply, did you still have that issue.

try to recompile if you using magento compile function and clear cache at var/cache
